server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  rabbitmq:
    host: ec-mq-rabbit
    port: 5672
    username: guest
    password: guest
  redis:
    host: ec-db-redis
    password: dev6373
    port: 6373
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
  boot:
    admin:
      username: admin
      password: admin
  security:
    user:
      password: admin
      name: admin



